version: "3.6"

services:
  history-api:
    build: ../history-api/.
    ports:
      - 5020:5020
    expose:
      - 5020
    container_name: history-api

  device-control-api:
    build: ../device-control-api/.
    ports:
      - 5010:5010
    expose:
      - 5010
    container_name: device-control-api

  user-api:
    build: ../user-api/.
    ports:
      - 5030:5030
    expose:
      - 5030
    container_name: user-api

  gateway-api:
    build: ../gateway-api/.
    ports:
      - 3000:3000
    container_name: gateway-api
    links:
      - history-api
      - device-control-api
      - user-api
